---
- name: Clone
  hosts: app
  tasks:
    - name: Install git
      become: true
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
